--- #YAML:1.0
name:               HTML-Form
version:            6.00
abstract:           Class that represents an HTML form element
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:               2
    HTML::TokeParser:     0
    HTTP::Request:        6
    HTTP::Request::Common:  6
    perl:                 5.008008
    URI:                  1.10
resources:
    MailingList:  mailto:libwww@perl.org
    repository:   http://github.com/gisle/libwww-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
